function(target_enable_lto TARGET ENABLED)
	if (NOT ${ENABLED})
		message(STATUS "LTO not SET")
		return()
	endif()

	include(CheckIPOSupported)
	check_ipo_supported(RESULT result OUTPUT output)

	if (result)
		message(STATUS "IPO/LTO supported")
		set_property(TARGET ${TARGET} PROPERTY INTERPROCEDURAL_OPTIMIZATION ON)
	else()
		message(WARNING "IPO/LTO not supported by compiler ${CMAKE_CXX_COMPILER_ID}")
	endif()
endfunction(target_enable_lto)
