function(enable_sanitizers)
	if (NOT ${SANITIZE_ENABLED})
		message(WARNING "Sanitizers NOT set")
		return()
	endif()
	message(STATUS "Sanitizers set")
	if (CMAKE_CXX_COMPILER_ID MATCHES "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "CLANG")
		add_compile_options("-fno-omit-frame-pointer")
		add_link_options("-fno-omit-frame-pointer")

		add_compile_options("-fsanitize=address")
		add_link_options("-fsanitize=address")
		add_compile_options("-fsanitize=undefined")
		add_link_options("-fsanitize=undefined")
	elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
		add_compile_options("/fsanitize=address")
		message(WARNING "undefined sanitizer not yet supported for MSVC")
	endif()
endfunction(enable_sanitizers)
